version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"      